### ISSUE TITLE
invisible Recaptcha

### ISSUE THREAD

**Issue by jayswamidass** [arjayosma/expo-firebase-phone-authentication#3]
Hi, how do you think I could modify your code to include an invisible recaptcha? Many thanks in advance.

**Comment by arjayosma** [comment]
Hi @jayswamidass, sorry for the late response. This is something we can explore.
Haven't tried it though, I'll see what I can come up with using Expo's APIs.

--

Closing this for now since it's still being explored. Thanks!

--

@jayswamidass Maybe you can take a look at this new props: https://docs.expo.io/versions/latest/sdk/firebase-recaptcha/#basic-usage

It's still experimental though, let me know how it works on your end.
